### ISSUE TITLE
Do URL-relative protocols always get normalized to http not https?

### ISSUE THREAD

**Issue by mnpenner** [sindresorhus/normalize-url#37]
Because that seems wrong. They should be normalized to what the current page is actually using, or `https` if not in a browser context.

**Comment by sindresorhus** [comment]
Yes, that's because `https` often does not resolve at all for sites not supporting `https`, so can't default to that. This module is not tied to a specific environment, so it has no knowledge (nor should it) of what page it's on when used in the browser. See the `normalizeHttps` option.

If you need it to be page aware, you could do `normalizeHttps: location.protocol === 'https:'`

**Comment by mnpenner** [comment]
Hrmm... I think I'd still learn towards https due to the security aspect, and if they were concerned about compatibility they could change the option. i.e., secure by default.

Anyway, thanks for the work around. I'll use that, thanks!
